In [58]:
import pandas as pd
import numpy as np

In [59]:
serum = pd.read_csv('D:\GitHub\\4BIT\metabolites\dataset\serum_processed.csv')
serum = serum.drop(['Unnamed: 0'], axis=1)
serum

,1_5-anhydroglucitol,1-monostearin,2_3-dihydroxybutanoic acid NIST,2_4-diaminobutyric acid,2-deoxyerythritol,2-deoxytetronic acid,2-hydroxybutanoic acid,2-hydroxyglutaric acid,2-hydroxyhippuric acid,2-hydroxyvaleric acid,...,tryptophan,tyrosine,UDP-glucuronic acid,urea,uric acid,uridine,valine,xylitol,xylose,Class
0,9582,279,82,61,357,122,24944,56,32,966,...,34239,54924,43,226295,11606,68,153849,194,811,disease
1,28847,161,78,84,205,258,10680,104,49,1076,...,20080,37597,203,96226,10188,71,110735,294,910,disease
2,13627,162,53,133,139,159,27201,160,80,1117,...,29191,28707,211,155596,16617,123,95509,253,804,disease
3,20758,6671,93,78,335,225,32347,242,59,304,...,16637,27873,71,191671,15214,84,96219,157,806,disease
4,15692,108,98,69,250,120,18357,60,25,1220,...,29820,30132,200,333019,20281,62,159853,188,1226,disease
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,25194,108,106,32,127,185,23821,53,103,1334,...,34521,35970,92,262448,18757,54,108092,180,748,control
78,23525,83,140,261,167,181,12396,65,39,1408,...,28112,28014,104,310051,26134,50,134469,211,651,control
79,25154,418,90,307,284,100,11788,124,106,997,...,39591,37287,166,295930,21733,69,82547,457,749,control
80,12397,110,104,56,342,186,15214,47,129,924,...,29273,23742,1903,276190,17275,68,112921,1256,526,control
81,18350,73,179,86,279,197,16085,60,198,899,...,23651,32068,69,152978,24358,61,134869,144,1823,control

In [60]:
serum = serum.drop(columns = ["Class"])

In [61]:
head = serum.head()
head

,1_5-anhydroglucitol,1-monostearin,2_3-dihydroxybutanoic acid NIST,2_4-diaminobutyric acid,2-deoxyerythritol,2-deoxytetronic acid,2-hydroxybutanoic acid,2-hydroxyglutaric acid,2-hydroxyhippuric acid,2-hydroxyvaleric acid,...,trans-4-hydroxyproline,tryptophan,tyrosine,UDP-glucuronic acid,urea,uric acid,uridine,valine,xylitol,xylose
0,9582,279,82,61,357,122,24944,56,32,966,...,2492,34239,54924,43,226295,11606,68,153849,194,811
1,28847,161,78,84,205,258,10680,104,49,1076,...,3428,20080,37597,203,96226,10188,71,110735,294,910
2,13627,162,53,133,139,159,27201,160,80,1117,...,2796,29191,28707,211,155596,16617,123,95509,253,804
3,20758,6671,93,78,335,225,32347,242,59,304,...,3161,16637,27873,71,191671,15214,84,96219,157,806
4,15692,108,98,69,250,120,18357,60,25,1220,...,5552,29820,30132,200,333019,20281,62,159853,188,1226

In [68]:
plasma_list = ['asparagine',
                'benzoic acid',
                'tryptophan',
                'uric acid',
                '5-hydroxynorvaline NIST',
                'alpha-ketoglutarate',
                'citrulline',
                'glutamine',
                'hypoxanthine',
                'malic acid',
                'methionine sulfoxide',
                'nornicotine',
                'octadecanol',
                '3-phosphoglycerate',
                '5-methoxytryptamine',
                'adenosine-5-monophosphate',
                'aspartic acid',
                'lactic acid',
                'maltose',
                'maltotriose',
                'N-methylalanine',
                'phenol',
                'phosphoethanolamine',
                'pyrophosphate',
                'pyruvic acid',
                'taurine']
serum_list = ['cholesterol',
            'lactic acid',
            'N-methylalanine',
            'phenylalanine',
            'aspartic acid',
            'deoxypentitol',
            'glutamic acid',
            'malic acid',
            'phenol',
            'taurine']

In [84]:
head.to_json('sample_data_serum.json' , orient = "records" , lines = True)

import json 

new_list = []
for i in range(len(head)) : 
    temp_list = []
    for j in plasma_list : 
        temp_list.append(head.loc[i,j])
    new_list.append(temp_list)

    with open('sampple_plasma_data.json', 'w', encoding='utf-8') as f:
        json.dump(temp_list, f, ensure_ascii=False, indent=4)


new_list

TypeError: Object of type int64 is not JSON serializable

In [63]:
plasma =pd.read_csv("D:\GitHub\\4BIT\metabolites\dataset\plasma_processed.csv")
plasma.head()

,Unnamed: 0,1_5-anhydroglucitol,1-monostearin,2_3-dihydroxybutanoic acid NIST,2_4-diaminobutyric acid,2-deoxyerythritol,2-deoxytetronic acid,2-hydroxybutanoic acid,2-hydroxyglutaric acid,2-hydroxyhippuric acid,...,tryptophan,tyrosine,UDP-glucuronic acid,urea,uric acid,uridine,valine,xylitol,xylose,Class
0,1,9483,103,101,963,389,123,20744,139,36,...,27450,52403,73,255067,10057,63,157332,154,1380,disease
1,2,27468,207,155,335,227,178,8611,78,91,...,17898,37179,157,180080,8386,118,103083,324,929,disease
2,3,13976,86,78,176,152,83,22792,92,97,...,29503,30670,211,138861,15822,119,92045,253,610,disease
3,4,19449,178,104,467,270,157,29418,123,92,...,16501,27573,71,183633,14024,102,97349,223,746,disease
4,5,17209,258,103,979,314,211,16713,76,42,...,24023,30096,222,255081,23154,58,159671,189,2022,disease

In [64]:
plasma.drop(['Unnamed: 0'], axis=1 , inplace = True)

In [65]:
plasma.drop(['Class'] , axis = 1 , inplace = True)
plasma.head()

,1_5-anhydroglucitol,1-monostearin,2_3-dihydroxybutanoic acid NIST,2_4-diaminobutyric acid,2-deoxyerythritol,2-deoxytetronic acid,2-hydroxybutanoic acid,2-hydroxyglutaric acid,2-hydroxyhippuric acid,2-hydroxyvaleric acid,...,trans-4-hydroxyproline,tryptophan,tyrosine,UDP-glucuronic acid,urea,uric acid,uridine,valine,xylitol,xylose
0,9483,103,101,963,389,123,20744,139,36,955,...,2248,27450,52403,73,255067,10057,63,157332,154,1380
1,27468,207,155,335,227,178,8611,78,91,103,...,2926,17898,37179,157,180080,8386,118,103083,324,929
2,13976,86,78,176,152,83,22792,92,97,1010,...,2862,29503,30670,211,138861,15822,119,92045,253,610
3,19449,178,104,467,270,157,29418,123,92,289,...,3036,16501,27573,71,183633,14024,102,97349,223,746
4,17209,258,103,979,314,211,16713,76,42,1126,...,4357,24023,30096,222,255081,23154,58,159671,189,2022

In [66]:
head2 = plasma.head()
head2

,1_5-anhydroglucitol,1-monostearin,2_3-dihydroxybutanoic acid NIST,2_4-diaminobutyric acid,2-deoxyerythritol,2-deoxytetronic acid,2-hydroxybutanoic acid,2-hydroxyglutaric acid,2-hydroxyhippuric acid,2-hydroxyvaleric acid,...,trans-4-hydroxyproline,tryptophan,tyrosine,UDP-glucuronic acid,urea,uric acid,uridine,valine,xylitol,xylose
0,9483,103,101,963,389,123,20744,139,36,955,...,2248,27450,52403,73,255067,10057,63,157332,154,1380
1,27468,207,155,335,227,178,8611,78,91,103,...,2926,17898,37179,157,180080,8386,118,103083,324,929
2,13976,86,78,176,152,83,22792,92,97,1010,...,2862,29503,30670,211,138861,15822,119,92045,253,610
3,19449,178,104,467,270,157,29418,123,92,289,...,3036,16501,27573,71,183633,14024,102,97349,223,746
4,17209,258,103,979,314,211,16713,76,42,1126,...,4357,24023,30096,222,255081,23154,58,159671,189,2022

In [67]:
head2.to_json('sample_data_serum.json' , orient = 'records' , lines= True)